theme: jekyll-theme-minimal
title: Gudon.ch ✊
description: pushing open society
# logo: "/assets/images/just-the-docs.png"
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
